/dadosabertos/comissao/agenda/mes/{mesReferencia}

```{r browser}
options(browser="firefox")
```

```{r }
ano_mes <- "202412"
versao = "2"

# https://legis.senado.leg.br/dadosabertos/comissao/agenda/mes/202412?v=2
URL <- paste0(baseURL, "comissao/agenda/mes/", ano_mes, "?v=", versao)
http <- httr::GET(URL)

content <- http$content |> rawToChar() |> jsonlite::fromJSON()
content$AgendaReuniao
content$AgendaReuniao$noNamespaceSchemaLocation
content$AgendaReuniao$Metadados

DF <- content$AgendaReuniao$reunioes |> 
  dplyr::bind_rows() |> 
  tibble::as_tibble() |> 
  dplyr::mutate(versao = as.Date(versao))

DF |> gt::gt()
DF$versao
DF$descricao
DF$titulo
DF$tipo
DF$


DF$partes |>  dplyr::bind_rows() |> tibble::as_tibble()
```

meetings
'https://legis.senado.leg.br/dadosabertos/comissao/reuniao/notas/13219?v=1'
"/dadosabertos/comissao/reuniao/{codigoReuniao}"
'/dadosabertos/comissao/reuniao/notas/{codigoReuniao}'
```{r }
paste0("https://legis.senado.leg.br/",
    "dadosabertos/",
    # "comissoes/comissao?codcol=", 
    "comissao?codcol=", 
    cod, "&data1=", start_date, "&data2=", end_date, "?v=1" 
  ) |> urltools::url_encode() |> 
  browseURL()

```
```{r }
meetings <- function(cod, start_date, end_date = Sys.Date() ){
  # https://legis.senado.leg.br/dadosabertos/api-docs/swagger-ui/index.html#/Comiss%C3%A3o/listaColegiadosSFPorTipo
# url = "https://legis.senado.leg.br/comissoes/comissao?codcol=2606&data1=2023-05-25&data2=2023-08-12"
  # cod = "2606"; start_date = "2023-05-25"; end_date = "2023-08-12"


    # extract the code if the code provided is not only numbers
  if (!stringr::str_detect(cod, "^\\d+$") ) {
    cod <- stringr::str_replace(cod , ".*codcol=(\\d+).*", "\\1")
  }

  url <- paste0( "https://legis.senado.leg.br/",
    "dadosabertos/",
    # "comissoes/comissao?codcol=", 
    "comissao?codcol=", 
    cod, "&data1=", start_date, "&data2=", end_date, "?v=1" 
  ) |> urltools::url_encode()

  browseURL(url)
  reunioes <- rvest::read_html(url)

  url |> 



  # data_start <- get_start_date(reunioes)
  # if(exists(data_start)){
  #   message(paste("Sugested begin data: ", as.character(data_start) ))
  # }

#  reunioes.vetor <- reunioes %>% rvest::html_elements('.row:nth-child(2) .content .col-md-12')
  reunioes.vetor <- reunioes |> rvest::html_elements('#reunioesAgendaComissao')

  datas.vetor <- reunioes.vetor  %>% rvest::html_element('a:nth-child(1) span:nth-child(1)') %>% rvest::html_text() %>%
    grep("^$", .,value=T, invert = T) %>%
    gsub("([0-9]{2})/([0-9]{2})/([0-9]{4})", "\\3-\\2-\\1", .)

  reuniao_dia <-  reunioes.vetor %>% rvest::html_element('span+ span') %>% rvest::html_text()  %>%
    grep("Reunião", .,value = T) %>%
    gsub("([0-9]+).*Reunião.*", "\\1", .) %>% as.integer()

  Depoente.tema <-  reunioes.vetor  %>% rvest::html_element('.f2') %>% rvest::html_text()

  link <- reunioes.vetor  %>% rvest::html_element('.bgc-cpi:nth-child(4) a, .bgc-cpmi:nth-child(4) a') %>% rvest::html_attr('href')

 reunDF <- tibble::tibble(data = datas.vetor,
                          reuniao_dia, Depoente.tema, link)
 # metadata = list(cod = cod)
 attr(reunDF, "cod") <- cod

 reunDF
}

```

 'https://legis.senado.leg.br/dadosabertos/comissao/reuniao/1500?v=2'

```{r }
paste0("https://legis.senado.leg.br/",
    "dadosabertos/",
    # "comissoes/comissao?codcol=", 
    "comissao/reuniao/", 
    cod,  "?v=2" 
  ) |> #urltools::url_encode() |> 
  browseURL()

```

## mesReferencia
/dadosabertos/comissao/agenda/mes/{mesReferencia}
```{r mesReferencia}
mesReferencia <- 202412

paste0("https://legis.senado.leg.br/",
    "dadosabertos/",
    "comissao/agenda/mes/", 
  mesReferencia,
  "?v=2") |> #urltools::url_encode() |> 
  browseURL()
```
I have this API call. Transform it into httr2 in R 

curl -X 'GET' \
  'https://legis.senado.leg.br/dadosabertos/comissao/agenda/mes/202412?v=2' \
  -H 'accept: text/csv'

```{r }
ano_mes <- 202412

search_agenda <- paste0("https://legis.senado.leg.br/dadosabertos/comissao/agenda/mes/", 
  ano_mes, "?v=2") |> 
  httr2::request() |>
  httr2::req_method("GET") |>
  # httr2::req_headers(accept = "text/csv") |> # too slow or doesnt works
  httr2::req_headers(accept = "application/json") |>
  httr2::req_perform()

body <- search_agenda$body |> rawToChar() |> jsonlite::fromJSON()

DF <- body$AgendaReuniao$reunioes[[1]] |> tibble::as_tibble()

knitr::kable(DF, format = "html")
DT::datatable(DF)
DF |> dplyr::count(descricao, sort=TRUE) 

DF$descricao[9]
DF$dataReuniao
DF$informacao
```
