#' get_all_tn
#'
#' get all  tacquigraphic notes from one commission (obtained by reunion() ) and
#'  structures all in one dataframe
#'
#' @param DF The dataframe generated by reunion()
#'
#' @examples
#' get_all_NT(DF)
#'
#' @export
get_all_tn <- function(DF){
   DF2 <- DF |> dplyr::filter(!is.na( link ))

  parser2 <- function(DFpars, i) {
    message(paste("running", i, "of", nrow(DFpars) ))
    dfpars <- parser(DFpars, i)
    message("waiting 3 seconds until the next requisition")
    Sys.sleep(3)
    dfpars }

  lapply(1:nrow(DF2), function(x) parser2(DF2, x)) |>  purrr::reduce(rbind)
}
